remove cleanup as Jenkins will do it.

diff --git a/Tests/EndToEndTests/EvalClientTests/CPPEvalClientTest/run-test b/Tests/EndToEndTests/EvalClientTests/CPPEvalClientTest/run-test
--- a/Tests/EndToEndTests/EvalClientTests/CPPEvalClientTest/run-test
+++ b/Tests/EndToEndTests/EvalClientTests/CPPEvalClientTest/run-test
@@ -2,28 +2,24 @@
 
 . $TEST_ROOT_DIR/run-test-common
 
-# Copy pretrained models and data
+# This test case is to test CSEvalClient works with the same setup of users. 
+# For that purpose, the test needs to create some models and data in the Examples directories as expected by CSEvalClient.
+# These files are removed by Jenkins during workspace cleanup.
+
 ImageDir=$TEST_ROOT_DIR/../../Examples/Image
 MnistDir=$ImageDir/MNIST
 DataDir=$MnistDir/Data
 ConfigDir=$MnistDir/Config
 OutputDir=$MnistDir/Output
 
-cleanupAndExit()
-{
-  #Delete Model data
-  rm -rf $OutputDir  
-  exit $1
-}
-
 # Train model for evaluation
-[ -d $OutputDir ] || mkdir $OutputDir || cleanupAndExit 1
+[ -d $OutputDir ] || mkdir $OutputDir || exit 1
 [ -d $OutputDir/Models ] && rm -rf $OutputDir/Models
 DeleteModelsAfterTest=0
 
-[ -f $ConfigDir/01_OneHidden.cntk ] || cleanupAndExit 1
+[ -f $ConfigDir/01_OneHidden.cntk ] || exit 1
 
-cntkrun 01_OneHidden.cntk "command=trainNetwork trainNetwork=[SGD=[maxEpochs=1]]" || cleanupAndExit 1
+cntkrun 01_OneHidden.cntk "command=trainNetwork trainNetwork=[SGD=[maxEpochs=1]]" || exit 1
  
 if [ "$OS" == "Windows_NT" ]; then
   $TEST_BIN_DIR/CPPEvalClientTest.exe
@@ -31,5 +27,4 @@ else
   $TEST_BIN_DIR/cppevalclient
 fi
 
-cleanupAndExit $?
-
+exit $?
